home.title=Welcome to spring Boot MVC
home.link=register Employee

emp.enter.title=Employee Register Page
emp.enter.id=Employee id
emp.enter.name=Employee name
emp.enter.Department=Employee Department
emp.enter.salary=Employee salary
emp.bt.page=Submit